### ISSUE TITLE
2D ResNet initialization

### ISSUE THREAD

**Issue by Hussein-A-Hassan** [yliu1229/CPCTR#1]
Hello Yue Liu, many thanks for sharing your code.
I have a question regarding the ResNet 2d backbone and the self-supervised training procedure.

Did you use ImageNet pre-trained 2D ResNet model as a backbone ? 

In another words, Did you initialize the 2D ResNet backbone with weights of a model trained on ImageNet
and then use the 2D ResNet backbone as a feature extractor in the UCF101 pre-training ? 

Thanks

**Comment by yliu1229** [comment]
Thanks for the questions.

No, I didn't use a pretrained ResNet in my training, the model was trained from scratch.
But you can use a pretrained ResNet to expedite the training process if you wish.

**Comment by Hussein-A-Hassan** [comment]
Thank You Very Much for the clarification.
